### ISSUE TITLE
How to retrieve the built artifact ?

### ISSUE THREAD

**Issue by Julow** [nixbuild/nixbuild-action#10]
I would like to build a standalone binary in my CI (it's an android application), I would like to retrieve the result. In my case, the result closure is small but the build dependencies are big, so that makes sense.

`nix build` doesn't print the result store path and doesn't generate the `result` symlink when using a remote store. The option `-o` seems to have no effect.
My current solution is to call `nix build` twice:
```
        nix build --eval-store auto --store ssh-ng://eu.nixbuild.net \
          -f ./shell.nix debug-apk
        nix build -f ./shell.nix debug-apk
```

The first time to build on the remote store and the second to hopefully pull the result from the cache. This is not ideal.

It seems that this tool has been built with flakes in mind, so perhaps flakes have better remote-store mechanisms ?

**Comment by rickynils** [comment]
You can run `nix build --json ...`, it will then output something like this on stdout:

```
[{"drvPath":"/nix/store/7grz4ylh94a0cfffk3m1cwh3511la71k-test.drv","outputs":{"out":"/nix/store/pzzxqxjfwidlqdvwkgy4fndx6axbpm7d-test"}}]
```

**Comment by rickynils** [comment]
@Julow Sorry, I pressed the comment button to early. First run your build with the `--json` flag as above, extract the `out` path (with `jq` or similar) and then run:

```
nix copy --from ssh-ng://eu.nixbuild.net /nix/store/pzzxqxjfwidlqdvwkgy4fndx6axbpm7d-test
```

**Comment by Julow** [comment]
`nix build --json` works really well, thanks for your help!

My script looks like this. It would be great to have a full example in the documentation in the "Running Remote Builds" page.
```yaml
    - name: Build
      run: |
        store=ssh-ng://eu.nixbuild.net
        result=$(
          nix build --json --eval-store auto --store $store \
            -f ./shell.nix debug-apk \
          | jq -r '.[0].outputs.out'
        )
        nix copy --from $store $result
        mkdir -p _build
        cp $result/*.apk _build
```

The `--eval-store` option takes a "store url" as value. Do you think it would be possible to pass only something like `--eval-store nixbuild.net` and have the store url configured somewhere else ?

**Comment by rickynils** [comment]
Yes, it would absolutely be good to have this info about how to fetch build outputs in docs.nixbuild.net, I'll add it.

`--eval-store` tells Nix which store to use for _evaluation_. `auto` means the local Nix store. nixbuild.net can't be used as an evaluation store because we have still not implemented the needed parts of the Nix protocol for that. Besides, I haven't actually managed get `nix build` to use a plain remote Nix machine as evaluation store either, so there might be things missing from Nix too (`--eval-store` is a recent addition). And, it might not make sense to use a remote store for evaluation if you already have your Nix expressions locally.

> have the store url configured somewhere else

Do you mean like setting up `--eval-store` and `--store` in `nix.conf` to avoid having to give command line args for it? I would like that, but unfortunately Nix doesn't support it. I think it would be a reasonable for Nix to support it though.

**Comment by Julow** [comment]
> Do you mean like setting up --eval-store and --store in nix.conf to avoid having to give command line args for it?

No, I mean having "store name = store url" in nix.conf somehow to pass one option instead of two and to avoid passing the url. But I misunderstood what `--eval-store` did, thanks for the explanations.

Closing this because there's no issue. Thanks for all the help!
