### ISSUE TITLE
Add support for biscuit tokens

### ISSUE THREAD

**Issue by michaelpj** [nixbuild/nixbuild-action#33]
We got access to a shared company nixbuild.net account, with access controlled via biscuit tokens. However, I'm not sure I can actually use my token with this action currently.

**Comment by rickynils** [comment]
@michaelpj Could you try out the `biscuit` branch (#34)? The only thing you should need to change is to set the [nixbuild_token](https://github.com/nixbuild/nixbuild-action/blob/17107bac946b66c9804eecfb681b52053f5ee70c/action.yml#L27) input instead of the [nixbuild_ssh_key](https://github.com/nixbuild/nixbuild-action/blob/17107bac946b66c9804eecfb681b52053f5ee70c/action.yml#L7) input.

**Comment by michaelpj** [comment]
Will do when I get some time to test it!

**Comment by rickynils** [comment]
@michaelpj Thanks! We have been using the `biscuit` branch for our internal nixbuild.net builds for a couple of days now and it has been working well so far.

**Comment by michaelpj** [comment]
Seems to be working!

**Comment by rickynils** [comment]
@michaelpj This has been merged and [released](https://github.com/nixbuild/nixbuild-action/releases/tag/v16) now.

Also, I removed the `biscuit` branch before realizing that you are probably using it, sorry! Bump to v16 to fix that.

**Comment by michaelpj** [comment]
> Also, I removed the biscuit branch before realizing that you are probably using it, sorry! Bump to v16 to fix that.

Yep, I figured that out already :)
